# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: corilo/corems:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  
  paths:
    - .cache/pip

before_script:
  - export http_proxy=http://proxy01.pnl.gov:3128
  - export https_proxy=http://proxy01.pnl.gov:3128
  - export no_proxy=localhost,127.0.0.1,*.pnl.gov,*.pnnl.gov,10.17.128.1,10.17,10.16,172.26

stages:
  - test
  - run
  

#before_script:
  #
  
test-job:
  
  stage: test
  tags:
    - k8s 
    - rzr
    - codebuilds
    

    
  script:
    - python -m pip install -r requirements.txt
    - python -V  # Print out python version for debugging
    - python setup.py test
    - ls
    

run-job:

  stage: run
  tags:
    - k8s 
    - rzr
    - codebuilds
    

  script:
    
    
    - pip install --editable .
    #- enviroMS search-formula 215.09269
 
